export const API_INVOCATION = 'API_INVOCATION';

//loaders
export const ENABLE_LOADER = 'ENABLE_LOADER';
export const DISABLE_LOADER = 'DISABLE_LOADER';

// post list
export const POST_LIST = 'POST_LIST';
export const POST_LIST_SUCCESS = 'POST_LIST_SUCCESS';
export const POST_LIST_ERROR = 'POST_LIST_ERROR';
export const RESET_POST_LIST = 'RESET_POST_LIST';

// competition list
export const COMPETITION_LIST = 'COMPETITION_LIST';
export const COMPETITION_LIST_SUCCESS = 'COMPETITION_LIST_SUCCESS';
export const COMPETITION_LIST_ERROR = 'COMPETITION_LIST_ERROR';
export const RESET_COMPETITION_LIST = 'RESET_COMPETITION_LIST';

// get user
export const GET_USER_PROFILE = 'GET_USER_PROFILE';

// story list
export const STORY_LIST = ' STORY_LIST';
export const STORY_LIST_SUCCESS = ' STORY_LIST_SUCCESS';
export const STORY_LIST_ERROR = ' STORY_LIST_ERROR';

//
export const FETCH_GENRE_START = 'FETCH_GENRE_START';
export const FETCH_GENRE_SUCCESS = 'FETCH_GENRE_SUCCESS';
export const FETCH_GENRE_ERROR = 'FETCH_GENRE_ERROR';
export const FETCH_COMPETITION_START = 'FETCH_COMPETITION_START';
export const FETCH_COMPETITION_SUCCESS = 'FETCH_COMPETITION_SUCCESS';
export const FETCH_COMPETITION_ERROR = 'FETCH_COMPETITION_ERROR';
export const FETCH_POSTS_START = 'FETCH_POSTS_START';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR';
export const UPLOAD_POSTS_START = 'UPLOAD_POSTS_START';
export const UPLOAD_POSTS_SUCCESS = 'UPLOAD_POSTS_SUCCESS';
export const UPLOAD_POSTS_ERROR = 'UPLOAD_POSTS_ERROR';
export const ADD_TRACK_START = 'ADD_TRACK_START';
export const ADD_TRACK_SUCCESS = 'ADD_TRACK_SUCCESS';
export const ADD_TRACK_ERROR = 'ADD_TRACK_ERROR';
export const FETCH_STORY_START = 'FETCH_STORY_START';
export const FETCH_STORY_SUCCESS = 'FETCH_STORY_SUCCESS';
export const FETCH_STORY_ERROR = 'FETCH_STORY_ERROR';
export const COMPETITION_BEAT_VOTE_START = 'COMPETITION_BEAT_VOTE_START';
export const COMPETITION_BEAT_VOTE_SUCCESS = 'COMPETITION_BEAT_VOTE_SUCCESS';
export const COMPETITION_BEAT_VOTE_ERROR = 'COMPETITION_BEAT_VOTE_ERROR';
export const COMPETITION_BEAT_VOTE_UPDATE = 'COMPETITION_BEAT_VOTE_UPDATE';
export const COMPETITION_BEAT_VOTE_STATUS = 'COMPETITION_BEAT_VOTE_STATUS';
export const COMPETITION_VOTE_START = 'COMPETITION_VOTE_START';
export const COMPETITION_VOTE_SUCCESS = 'COMPETITION_VOTE_SUCCESS';
export const COMPETITION_VOTE_ERROR = 'COMPETITION_VOTE_ERROR';
export const COMPETITION_VOTE_SELECT = 'COMPETITION_VOTE_SELECT';
export const COMPETITION_RESULT_START = 'COMPETITION_RESULT_START';
export const COMPETITION_RESULT_SUCCESS = 'COMPETITION_RESULT_SUCCESS';
export const COMPETITION_RESULT_ERROR = 'COMPETITION_RESULT_ERROR';
export const COMPETITION_PRIZE_OPTION_START = 'COMPETITION_PRIZE_OPTION_START';
export const COMPETITION_PRIZE_OPTION_SUCCESS =
  'COMPETITION_PRIZE_OPTION_SUCCESS';
export const COMPETITION_PRIZE_OPTION_ERROR = 'COMPETITION_PRIZE_OPTION_ERROR';
export const ONLINE_COMPETITION_UPLOAD_START =
  'ONLINE_COMPETITION_UPLOAD_START';
export const ONLINE_COMPETITION_UPLOAD_SUCCESS =
  'ONLINE_COMPETITION_UPLOAD_SUCCESS';
export const ONLINE_COMPETITION_UPLOAD_ERROR =
  'ONLINE_COMPETITION_UPLOAD_ERROR';
export const COMPETITION_PARTICIPANT_STARTING =
  'COMPETITION_PARTICIPANT_STARTING';
export const COMPETITION_PARTICIPANT_STARTED =
  'COMPETITION_PARTICIPANT_STARTED';
export const COMPETITION_ROUND_STARTING = 'COMPETITION_ROUND_STARTING';
export const COMPETITION_ROUND_STARTED = 'COMPETITION_ROUND_STARTED';
export const COMPETITION_AD_STARTING = 'COMPETITION_AD_STARTING';
export const COMPETITION_AD_STARTED = 'COMPETITION_AD_STARTED';
export const COMPETITION_AD_ENDED = 'COMPETITION_AD_ENDED';
export const COMPETITION_PREROLL_STARTING = 'COMPETITION_PREROLL_STARTING';
export const COMPETITION_PREROLL_STARTED = 'COMPETITION_PREROLL_STARTED';
export const COMPETITION_PREROLL_ENDED = 'COMPETITION_PREROLL_ENDED';
export const COMPETITION_YOURTURN_STARTING = 'COMPETITION_YOURTURN_STARTING';
export const COMPETITION_YOURTURN_STARTED = 'COMPETITION_YOURTURN_STARTED';
export const COMPETITION_UPDATEPOINTS = 'COMPETITION_UPDATEPOINTS';
export const COMPETITION_ENDED = 'COMPETITION_ENDED';
export const COMPETITION_GET_SELF_DETAIL_START =
  'COMPETITION_GET_SELF_DETAIL_START';
export const COMPETITION_GET_SELF_DETAIL_SUCCESS =
  'COMPETITION_GET_SELF_DETAIL_SUCCESS';
export const COMPETITION_GET_SELF_DETAIL_ERROR =
  'COMPETITION_GET_SELF_DETAIL_ERROR';
export const COMPETITION_ACCEPT_TERM_CONDITION_SUCCESS =
  'COMPETITION_ACCEPT_TERM_CONDITION_SUCCESS';
export const COMPETITION_ACCEPT_TERM_CONDITION_ERROR =
  'COMPETITION_ACCEPT_TERM_CONDITION_ERROR';
export const COMPETITION_ACCEPT_TERM_CONDITION_START =
  'COMPETITION_ACCEPT_TERM_CONDITION_START';
export const COMPETITION_VIEWERS_ADDED = 'COMPETITION_VIEWERS_ADDED';
export const COMPETITION_PARTICIPANTS_ADDED = 'COMPETITION_PARTICIPANTS_ADDED';
export const COMPETITION_DETAILS_START = 'COMPETITION_DETAILS_START';
export const COMPETITION_DETAILS_SUCCESS = 'COMPETITION_DETAILS_SUCCESS';
export const COMPETITION_DETAILS_ERROR = 'COMPETITION_DETAILS_ERROR';
export const FETCH_INTEREST_START = 'FETCH_INTEREST_START';
export const FETCH_INTEREST_SUCCESS = 'FETCH_INTEREST_SUCCESS';
export const FETCH_INTEREST_ERROR = 'FETCH_INTEREST_ERROR';
export const CREATE_LIVE_STREAM_START = 'CREATE_LIVE_STREAM_START';
export const CREATE_LIVE_STREAM_SUCCESS = 'CREATE_LIVE_STREAM_SUCCESS';
export const CREATE_LIVE_STREAM_ERROR = 'CREATE_LIVE_STREAM_ERROR';
export const GET_SEHEDULE_START = 'GET_SEHEDULE_START';
export const GET_SEHEDULE_SUCCESS = 'GET_SEHEDULE_SUCCESS';
export const GET_SEHEDULE_ERROR = 'GET_SEHEDULE_ERROR';
export const GET_PHOTOS_IMAGE_VIDEOS_START = 'GET_PHOTOS_IMAGE_VIDEOS_START';
export const GET_PHOTOS_IMAGE_VIDEOS_SUCCESS =
  'GET_PHOTOS_IMAGE_VIDEOS_SUCCESS';
export const GET_PHOTOS_IMAGE_VIDEOS_ERROR = 'GET_PHOTOS_IMAGE_VIDEOS_ERROR';
export const FETCH_TRACKS_START = 'FETCH_TRACKS_START';
export const FETCH_TRACKS_SUCCESS = 'FETCH_TRACKS_SUCCESS';
export const FETCH_TRACKS_ERROR = 'FETCH_TRACKS_ERROR';
export const FETCH_USERPROFILE_START = 'FETCH_USERPROFILE_START';
export const FETCH_USERPROFILE_SUCCESS = 'FETCH_USERPROFILE_SUCCESS';
export const FETCH_USERPROFILE_ERROR = 'FETCH_USERPROFILE_ERROR';
export const FETCH_COMMENTS_PENDING = 'FETCH_COMMENTS_PENDING';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_FAILED = 'FETCH_COMMENTS_FAILED';
export const CANCEL_SUBSCRIPTION_START = 'CANCEL_SUBSCRIPTION_START';
export const CANCEL_SUBSCRIPTION_SUCCESS = 'CANCEL_SUBSCRIPTION_SUCCESS';
export const CANCEL_SUBSCRIPTION_ERROR = 'CANCEL_SUBSCRIPTION_ERROR';
export const COMPETITION_CONTESTANT_INFO_STARTING =
  'COMPETITION_CONTESTANT_INFO_STARTING';
export const COMPETITION_CONTESTANT_INFO_STARTED =
  'COMPETITION_CONTESTANT_INFO_STARTED';
export const POINTS_START = 'POINTS_START';
export const POINTS_SUCCESS = 'POINTS_SUCCESS';
export const POINTS_ERROR = 'POINTS_ERROR';
export const USER_UPDATE_START = 'USER_UPDATE_START';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_ERROR = 'USER_UPDATE_ERROR';
export const USER_DELETE_START = 'USER_DELETE_START';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_ERROR = 'USER_DELETE_ERROR';
export const TIER_PERMISSION_START = 'TIER_PERMISSION_START';
export const TIER_PERMISSION_SUCCESS = 'TIER_PERMISSION_SUCCESS';
export const TIER_PERMISSION_ERROR = 'TIER_PERMISSION_ERROR';
export const UPDATE_TIER_PERMISSION_START = 'UPDATE_TIER_PERMISSION_START';
export const UPDATE_TIER_PERMISSION_SUCCESS = 'UPDATE_TIER_PERMISSION_SUCCESS';
export const UPDATE_TIER_PERMISSION_ERROR = 'UPDATE_TIER_PERMISSION_ERROR';
export const NEW_COMMENTS = 'NEW_COMMENTS';
export const CLEAR_COMMENTS = 'CLEAR_COMMENTS';
export const UPDATE_USER_START = 'UPDATE_USER_START';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';
export const FETCH_USER_REFERRAL_START = 'FETCH_USER_REFERRAL_START';
export const FETCH_USER_REFERRAL_SUCCESS = 'FETCH_USER_REFERRAL_SUCCESS';
export const FETCH_USER_REFERRAL_ERROR = 'FETCH_USER_REFERRAL_ERROR';
export const REFERRAL_START = 'REFERRAL_START';
export const REFERRAL_SUCCESS = 'REFERRAL_SUCCESS';
export const REFERRAL_ERROR = 'REFERRAL_ERROR';

export const USER_CONNECTION_START = 'USER_CONNECTION_START';
export const USER_CONNECTION_SUCCESS = 'USER_CONNECTION_SUCCESS';
export const USER_CONNECTION_ERROR = 'USER_CONNECTION_ERROR';
export const FETCH_MODERATOR_USERPROFILE_START =
  'FETCH_MODERATOR_USERPROFILE_START';
export const FETCH_MODERATOR_USERPROFILE_SUCCESS =
  'FETCH_MODERATOR_USERPROFILE_SUCCESS';
export const FETCH_MODERATOR_USERPROFILE_ERROR =
  'FETCH_MODERATOR_USERPROFILE_ERROR';

export const POST_LIKE_START = 'POST_LIKE_START';
export const POST_LIKE_SUCCESS = 'POST_LIKE_SUCCESS';
export const POST_LIKE_ERROR = 'POST_LIKE_ERROR';

export const TEST = 'TEST';

//genre list
export const GENRE_LIST = 'GENRE_LIST';
export const GENRE_LIST_SUCCESS = 'GENRE_LIST_SUCCESS';
export const GENRE_LIST_ERROR = 'GENRE_LIST_ERROR';

//intrest list
export const INTREST_LIST = 'INTREST_LIST';
export const INTREST_LIST_SUCCESS = 'INTREST_LIST_SUCCESS';
export const INTREST_LIST_ERROR = 'INTREST_LIST_ERROR';

// local user data
export const SET_LOCAL_USERDATA = 'SET_LOCAL_USERDATA';
export const SET_STORY_SELECTED_URL = 'SET_STORY_SELECTED_URL';

// post UserData
export const USER_DATA = 'USER_DATA';
export const USER_DATA_SUCCESS = 'USER_DATA_SUCCESS';
export const USER_DATA_ERROR = 'USER_DATA_ERROR';

// post User story data
export const POST_STORY_DATA = 'POST_STORY_DATA';
export const POST_STORY_DATA_SUCCESS = 'POST_STORY_DATA_SUCCESS';
export const POST_STORY_DATA_ERROR = 'POST_STORY_DATA_ERROR';

//  User new post data
export const NEW_POST_DATA = 'NEW_POST_DATA';
export const NEW_POST_DATA_SUCCESS = 'NEW_POST_DATA_SUCCESS';
export const NEW_POST_DATA_ERROR = 'NEW_POST_DATA_ERROR';

// post User Data
export const USER_DATA_POST = 'USER_DATA_POST';
export const USER_DATA_POST_SUCCESS = 'USER_DATA_POST_SUCCESS';
export const USER_DATA_POST_ERROR = 'USER_DATA_POST_ERROR';
export const USER_DATA_POST_LIST = 'USER_DATA_POST_LIST';

// Media
export const MEDIA = 'MEDIA';
export const MEDIA_SUCCESS = 'MEDIA_SUCCESS';
export const MEDIA_ERROR = 'MEDIA_ERROR';

// userProfile Content Get
export const USER_PROFILE_CONTENT = 'USER_PROFILE_CONTENT'
export const USER_PROFILE_CONTENT_SUCCESS = 'USER_PROFILE_CONTENT_SUCCESS'
export const USER_PROFILE_CONTENT_ERROR = 'USER_PROFILE_CONTENT_ERROR'

//
export const COMPETITION_CHAT_CONTESTANT_ADDED = 'COMPETITION_CHAT_CONTESTANT_ADDED'
export const COMPETITION_CHAT_AUDIENCE_ADDED = 'COMPETITION_CHAT_AUDIENCE_ADDED'
